name: Build Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mega_jupyter

jobs:
  build-and-push-image:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: MattFlower  
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/mattflower/mega_jupyter:latest
